import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {/* So, you want to travel to
      Space
      Let’s face it; if you want to go to space, you might as well genuinely go to
      outer space and not hover kind of on the edge of it. Well sit back, and relax
      because we’ll give you a truly out of this world experience!

      Explore */}

    </div>
  )
      
}

export default Home
